### ISSUE TITLE
Taking over this feedstock 

### ISSUE THREAD

**Issue by Hofer-Julian** [conda-forge/modflow6-feedstock#6]
@scopatz, we work on a Python app that would greatly benefit from this package: https://gitlab.com/deltares/imod/imod-python.
Since the last commit was last year, we assume that this package is abandoned. 
We offer take over the maintainership of this feedstock.
Please let us know how you feel about this.

@Huite @JoerivanEngelen

**Comment by xhochy** [comment]
Add yourself via the add user bot command and someone from conda-forge/core will merge it
